### ISSUE TITLE
feat: Allow defined but empty configuration values for the UI

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2098]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Actually, the UI `ConfigService` does not allow defined, but empty configuration values and exception "Error: No setting found with the specified group ..." (which is not true as there is such a setting but empty.

Actually in 

https://github.com/syndesisio/syndesis/blob/6cc64db216942d4ef3d5971ad65a6c9c52a16786/app/ui/src/app/config.service.ts#L65-L72

I would like to allow empty values, too (i.e. changing `!this.settingsRepository[group]` to `this.settingsRepository[group] === undefined`)

One reason for this change is that it would allow optional OpenShift template parameters to intialize config.json. As you might know, config.json is backed by a so called OpenShift `ConfigMap` which in turn is created from an OpenShift template instantiation during installation (that's happening to your cluster when you call `syndesis install` or `syndesis minishift`). The template instantiation takes several parameters from the outside which are then filled into the various openshift configmaps, like here for the UI config.json

```yaml
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: syndesis-ui-config
    labels:
      app: syndesis
      component: syndesis-ui
  data:
    config.json: |
      {
        "apiBase": "https://${ROUTE_HOSTNAME}",
        "apiEndpoint": "/api/v1",
        "title": "Syndesis",
        "openshiftConsolerUrl" : "${OPENSHIFT_CONSOLE_URL}",
        "datamapper": {
          "baseMappingServiceUrl": "https://${ROUTE_HOSTNAME}/api/v1/atlas/",
          "baseJavaInspectionServiceUrl": "https://${ROUTE_HOSTNAME}/api/v1/atlas/java/",
          "baseXMLInspectionServiceUrl": "https://${ROUTE_HOSTNAME}/api/v1/atlas/xml/",
          "baseJSONInspectionServiceUrl": "https://${ROUTE_HOSTNAME}/api/v1/atlas/json/"
        },
        "features" : {
          "logging": false
        },
        "branding": {
          "logoWhiteBg": "assets/images/syndesis-logo-svg-white.svg",
          "logoDarkBg": "assets/images/syndesis-logo-svg-white.svg",
          "iconWhiteBg": "assets/images/glasses_logo_square.png",
          "iconDarkBg": "assets/images/glasses_logo_square.png",
          "appName": "Syndesis",
          "favicon32": "/favicon-32x32.png",
          "favicon16": "/favicon-16x16.png",
          "touchIcon": "/apple-touch-icon.png",
          "productBuild": false
       }
      }
```

Please note here the various parameters with `${ROUTE_HOSTNAME}`. These are the parameters which gets filled in. This example contains now a parameter `${OPENSHIFT_CONSOLE_URL}` which is _optional_. That means the user does not need to provide this parameter. If the user does not provide it, this parameter is empty and you end up with an empty string in the configuration.

One could set a default value, but having a default value like e.g. "false" would shine through to the OpenShift UI when the user is asked for the parameters to be filled. Havin a value "false" in a text field for an URL however just feels wrong. Actually this feature is required for every optional parameter for which you would like to have an empty input field in the OpenShift console when instantiating the OpenShift template.

## Expected behavior

It would be awesome when I could convince you with this use case and allow defined, but empty values for configuration properties.
