### ISSUE TITLE
Support setting token strategy and authorize using parameters properties in API connectors

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2357]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Two properties that can be set for OAuth2 authentication:
 - token strategy (values: AUTHORIZATION_HEADER, ACCESS_TOKEN_PARAMETER and OAUTH_TOKEN_PARAMETER)
 - authorize using parameters (values: true/false)

Cannot be determined from a Swagger specification. We should add support for setting those via vendor extensions on Swagger `securityDefinition` to allow fine tuning OAuth2 support for created API connectors.

## Expected behavior

Setting vendor extensions on Swagger specification's `securityDefiniton` should influence the way OAuth2 flow is executed:
 - setting `x-token-strategy` vendor extension to:
    - AUTHORIZATION_HEADER (default): indicates that the access token should be carried in the Authorization header as an OAuth2 Bearer token
    - ACCESS_TOKEN_PARAMETER: indicates that the access token should be carried as a query parameter named "access_token"
    - OAUTH_TOKEN_PARAMETER: indicates that the access token should be carried as a query parameter named "oauth_token"
  - setting `x-authorize-using-parameters` to `true` (`false` is default) will pass client credentials to the provider as parameters instead of using HTTP Basic authentication.

Example Swagger specification:
```yaml
securityDefinitions:
  concur_oauth2:
    type: 'oauth2'
    flow: 'accessCode'
    authorizationUrl: 'https://us-impl.api.concursolutions.com/oauth2/v0/authorize'
    tokenUrl: 'https://us-impl.api.concursolutions.com/oauth2/v0/token'
    scopes:
      LIST: Access List API
    x-token-strategy: AUTHORIZATION_HEADER
    x-authorize-using-parameters: true
```

## Tasks involved / Steps to Reproduce

1. Add property generator for token strategy and authorize using parameters properties to connector template
2. Implement property generator for token strategy and authorize using parameters properties
