### ISSUE TITLE
"Syndesis" CRD

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2889]
Defined a customer resource for holding template parameter values and other information required for instantiating syndesis as app.

The name could be e.g. either `Syndesis` or `FuseOnline`. Not sure whether we should make this configurable or just stick to `Syndesis` and introduce only `FuseOnline` if there will be a _difference_

But maybe we should already introduce both, so that we distinguish the templates to apply based on the resource type ? Guess that's not so bad anyway.

**Comment by rhuss** [comment]
The idea is to define two resources:

* `Syndesis` for an upstream installation
* `FuseOnline` for a product installation

These resources are nearly identical but they trigger different templates to be applied by the operator (the upstream and the productised templates).

The scope of this story is define the resource along with the JSON schema for validation. See also the design proposal of an example already.

**Comment by rhuss** [comment]
The example looks like:

```yaml
kind: Syndesis
apiVersion: syndesis.io/v1
metadata:
  name: syndesis
  version: 1.4.2
spec:
      routeHostName: ${project}.6a63.fuse-ignite.openshiftapps.com
      demoData: false
      maxIntegrations: 5
      postgresql:
        memoryLimit: 255Mi
        user: syndesis
      prometheus:
        memoryLimit: 512Mi
    volumeSize: 1Gi
      server:
        memoryLimit: 800Mi
  meta:
    memoryLimit: 512Mi
  ...
```
