### ISSUE TITLE
Template for upgrade pod for OCP misses registry reference.

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3440]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

The template for the upgrade pod in the main template for the productised image references the image without registry. I don't think this work, I think it should point to image in the registry (now its looked up in docker hub)

```yaml
- apiVersion: template.openshift.io/v1
  kind: Template
  ....
  objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: syndesis-upgrade-${SYNDESIS_VERSION}
    spec:
      containers:
        image: fuse7/fuse-ignite-upgrade:1.1-2
      ....
```

cc @heiko-braun
