### ISSUE TITLE
'Unable to mount volumes for pod "syndesis-upgrade-1.4.7...' during upgrade from 1.4.6 to 1.4.7 on OSO pro

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3460]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I'm unable to upgrade syndesis on openshift pro:

3:31:18 PM | Warning | Failed Mount | Unable to mount volumes for pod "syndesis-upgrade-1.4.7_upgrade-project(ee1e559b-a9fb-11e8-937e-125b034d2f46)": timeout expired waiting for volumes to attach/mount for pod "upgrade-project"/"syndesis-upgrade-1.4.7". list of unattached/unmounted volumes=[backup-dir]5 times in the last 10 minutes
-- | -- | -- | --
3:20:13 PM | Normal | Successful Mount Volume | MountVolume.SetUp succeeded for volume "syndesis-operator-token-jwf4x"
3:20:13 PM | Warning | Failed Attach Volume | Multi-Attach error for volume "pvc-655fe43a-a9fb-11e8-ba69-12b5519f9b58" Volume is already used by pod(s) syndesis-db-1-2m8n5
3:20:13 PM | Normal | Scheduled | Successfully assigned syndesis-upgrade-1.4.7 to ip-172-31-58-128.ec2.internal

![screen shot 2018-08-27 at 15 26 39](https://user-images.githubusercontent.com/6814482/44662533-53faa780-aa0e-11e8-8bfa-5ec1fc60d752.png)

## Tasks involved / Steps to Reproduce

1. deploy syndesis 1.4.6 on OSO Pro using template
2. manually create operator service account 
3. try to upgrade to 1.4.7 via template ("old way")

**Comment by mmelko** [comment]
@kcbabo @heiko-braun @gaughan @rhuss  wdyt ?

**Comment by gaughan** [comment]
@rhuss @mmelko  Is it valid to upgrade via template after creating an operator service account?

**Comment by kcbabo** [comment]
Given that we will be rolling out upgrades on the Pro cluster, is there a manual workaround to this problem?

**Comment by heiko-braun** [comment]
@mmelko Since you'd been using the template based approach in step 1 and 3, why did you create the service account in step 2? What are we testing here? 

I would expect that once a decision for using the template based installation has bee taken, no further operator related steps are needed.

**Comment by heiko-braun** [comment]
@nicolaferraro What are your thoughts on this?

**Comment by avano** [comment]
@heiko-braun that is probably a bug in the syndesis template, that was used to deploy syndesis in a "old way".

As you can see here in the 1.4.6 tag, the syndesis-upgrade references the syndesis-operator service account, even when you don't use operator at all:
https://github.com/syndesisio/syndesis/blob/syndesis-1.4.6.fuse-710001/install/syndesis.yml#L1632

When Matej tried to upgrade using the "old" way without operator, the upgrade pod immediately failed because it could not find `syndesis-operator` service account. So he tried to create the service account for the operator manually to see if he will be able to upgrade afterwards, but he ended up with this issue.

That is how I recall it, probably we should open a new issue for referencing the syndesis-operator service account in the "old way" template

**Comment by avano** [comment]
@heiko-braun I created #3514 for referencing the operator SA

**Comment by nicolaferraro** [comment]
The template is referencing the operator service-account, so it is not good for "old school" upgrade via template.
But if you manage to create the operator service-account manually, it should work (it has higher privileges than the "old school" one).

I think the real problem is that the database volume was (and still is) marked as `ReadWriteOnce` here: https://github.com/syndesisio/syndesis/blob/8aaa5b38d01525f7c5298e8c53f86da6ccb1027d/install/syndesis.yml#L530.

But it's then mounted also in the upgrade pod for backup purposes: https://github.com/syndesisio/syndesis/blob/155984e5c7c020260884324df6488be832caea7b/install/syndesis.yml#L1652.

So, the error message is correct. This configuration works on Minishift and occasionally on small clusters, but often fails in clusters composed of several nodes.

The access level `ReadWriteOnce` allows a volume to be bound to at most one physical node, so the upgrade should work only when the upgrade pod is scheduled on the same physical node of the database pod.

As workaround, if the cluster is not too big, deleting the upgrade pod and retrying the upgrade will eventually work.

To have a proper fix, the volume access mode should be changed to `ReadWriteMany`. I don't know if that can be done on a existing volume.

**Comment by nicolaferraro** [comment]
@mmelko can you check if my understanding is correct?

If that is the case, the issue may be mitigated with [inter pod affinity rules](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature) on the template.

**Comment by heiko-braun** [comment]
@avano Thanks I now see why step 3 was needed. The template is used by the operator and hence carries the service account. 

I think it can stay that way if we document that these steps are needed. 

But the clarify the needs:

We need to support both approches, with and without an operator, for now. @nicolaferraro How do you think can this be best achieved?

**Comment by nicolaferraro** [comment]
@mmelko, right.. You can try directly with these affinity rules (should be easier):

```
apiVersion: v1
kind: Pod
metadata:
  name: syndesis-upgrade-1.4.7
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: "syndesis.io/app"
            operator: In
            values:
            - "syndesis"
          - key: "syndesis.io/component"
            operator: In
            values:
            - "syndesis-db"
        topologyKey: "kubernetes.io/hostname"
  serviceAccountName: syndesis-operator
  containers:
  - name: upgrade
    image: syndesis/syndesis-upgrade:1.4.7
    env:
      - name: SYNDESIS_UPGRADE_PROJECT
        valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
    imagePullPolicy: IfNotPresent
    args:
      - "--backup"
      - "/opt/backup"
    volumeMounts:
    - mountPath: /opt/backup
      subPath: backup
      name: backup-dir
  volumes:
  - name: backup-dir
    persistentVolumeClaim:
      claimName: syndesis-db
  restartPolicy: Never
```
