### ISSUE TITLE
Introduce stalebot

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#3579]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

Configure probot/stale for this repo with a stale threshold of 60 days. 
See probot.github.io/apps/stale and probot/stale and this sample config:

```yaml
daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - priority/p0
staleLabel: pr/stale
markComment: >
  This issue has been automatically marked as stale because it has not had any activity since 60 days. It will be closed if no further activity occurs within 7 days. Thank you for your contributions !
closeComment: false
only: issues
```
