### ISSUE TITLE
Add 3scale exposure configuration to OpenShift template/operator

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3733]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
On Syndesis server install the `syndesis-server` pod determines if the 3scale exposure via service discovery is enabled or not. This is done via environment variable `CONTROLLERS_EXPOSE_VIA3SCALE` if has `true` as value 3scale integration will be enabled.

We should surface this to the OpenShift template and through the Syndesis operator.

**Comment by zregvart** [comment]
I'd rather have this exposed in the template for this sprint and make it configurable by the end user in #3708.

**Comment by mcada** [comment]
Verified with following template:
```
# Syndesis installation parameters with default values used
# All of them are optional except 'routeHostname' for now
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: "example"
spec:
  # Name of the route how to access Syndesis (optional)
  #routeHostname: syndesis.192.168.64.79.nip.io
  # Enable demo data (or not)
  demoData: false
  # Should deployment of integrations be enabled?
  deployIntegrations: true
  imageStreamNamespace: ""
  integration:
    # How many integration are allowed ?
    limit: 1
    # How to check for state changes ?
    stateCheckInterval: 60
  # Registry from where to pickup images
  registry: docker.io
  # Component specific configuration
  components:
    db:
      resources:
        limits:
          memory: 255Mi
        volumeCapacity: 1Gi
      # DB user
      user: syndesis
      # DB name
      database: syndesis
      imageStreamNamespace: openshift
    prometheus:
      resources:
        limits:
          memory: 512Mi
        volumeCapacity: 1Gi
    server:
      resources:
        limits:
          memory: 800Mi
      features:
        exposeVia3Scale: true
    meta:
      resources:
        limits:
          memory: 512Mi
        volumeCapacity: 1Gi
    upgrade:
      resources:
        volumeCapacity: 1Gi
```
