### ISSUE TITLE
Use targetPort instead of port for Prometheus ServiceMonitor resources

### ISSUE THREAD

**Issue by jamesnetherton** [syndesisio/syndesis#4967]
Currently our ServiceMonitor specs look like:

```
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      syndesis.io/component: syndesis-db
```

In this example, using 'port' requires an exposed port named 'metrics' on the service related to the label selector. This is not strictly required or necessary. The ServiceMonitor can monitor ports of backing pods, that are not part of the service endpoints by using `targetPort`. E.g:

```
spec:
  endpoints:
  - targetPort: metrics
```
