### ISSUE TITLE
[Apicurito operator] - CRD cannot be deleted

### ISSUE THREAD

**Issue by mmajerni** [syndesisio/syndesis#4978]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

An operator works fine but after tests when I am doing cleanup there is a problem with CRD. The CRD cannot be deleted. Command: 
`oc delete crd apicuritos.apicur.io`
This command never ends and CRD is in state "object is being deleted"

btw. other resources (Role, RoleBinding, ... ) have not this problem.

#4871

**Comment by mmajerni** [comment]
#4871

**Comment by lgarciaaco** [comment]
I think this is openshift not being able to delete resources in the right order, like the CR should be deleted when the CRD is gone, but this might not be the case

**Comment by lgarciaaco** [comment]
OK ... here is the thing: Something (I am guessing the operator itself) adds a [finalizer](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers) to the CRD. This can be some implementation within the operator-sdk (I am assuming, I didn't dig into the code) that is out of our control (because we are using helms and this gives as much as no control over the lifecicle of the application, as well as the helm templates, other than creating them). Facts are, after the CR is added and the application is created, the CRD looks like:

```
[lgarciaa@lgarciaa operator]$ oc get apicurito -o yaml                                                                                                                                                             
apiVersion: v1
items:
- apiVersion: apicur.io/v1alpha1
  kind: Apicurito
  metadata:
    creationTimestamp: 2019-03-20T10:59:48Z
    finalizers:
    - uninstall-helm-release
    generation: 1
    labels:
      app: apicurito
    name: apicurito
```
Notice the *uninstall-helm-release* part.

This is how I completely clean the namespace:
```
oc delete all -l app=apicurito
oc edit apicurito # Delete the finalizer block and save
oc delete crd apicuritos.apicur.io
```

@heiko-braun since we are using a not maintained version of the operator-sdk, it is ok to accept this work around to cleanup the apicurito installation? With a proper go operator we wont have this issue.

If needed, I could create a `uninstall.sh` script.
