### ISSUE TITLE
Support enabling Komodo via faux addons feature in the operator

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5433]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When we get the Komodo changes merged (#5358) we should add faux support for addons in the operator.

This implementation would be minimal and will support only toggling replicas number for the Komodo deployment configuration from 0 (default) to 1 (if enabled).

This could be used as a base for further addons support and for the addons idea done in #5399.

**Comment by zregvart** [comment]
The addons on the operator could be defined as:
```yaml
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: "example-with addons"
spec:
  addons:
    komodo:
      parameters:
        KOMODO_MEMORY_LIMIT: 1024
```

**Comment by zregvart** [comment]
This is the first super minimal and Komodo specific feature, we can use this principle, well, data structure, to install additional modules on top of the default ones.

Any thoughts welcome.

cc @astefanutti @lgarciaaco @nicolaferraro @lburgazzoli @phantomjinx @alexkieling @jamesnetherton

**Comment by zregvart** [comment]
We have this via #5439 sans the functionality to specify any additional parameters for the komodo addon. So to install via the Syndesis operator including komodo one should specify the following Syndesis resource:

```yaml
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: app
spec:
  addons:
    komodo:
```

The `komodo:` bit is not a typo.

**Comment by chirino** [comment]
https://github.com/syndesisio/syndesis/pull/6256 was just merged and which enables komodo via addon templates.  Those templates can be further enhanced to use any variables in the Syndesis CR. To enable Komodo, you do this now:

```
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: app
spec:
  addons:
    komodo:
      enabled: "true"
```
