### ISSUE TITLE
Continuous Integration improvement: Develop parallel connector build

### ISSUE THREAD

**Issue by balejos** [syndesisio/syndesis#5797]
As a result of our retrospective, we agreed to develop a parallel build that would execute the connectors so that the main build can run faster.

**Comment by squakez** [comment]
I'd like to give an hand on that, but it may take some time for me as I have to learn some basic about CircleCI. If we don't have any rush I can work on it

**Comment by christophd** [comment]
I can also join and give that a try.

**Comment by christophd** [comment]
This could be worth a try: https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

**Comment by christophd** [comment]
Let me share some idea how we could do parallel builds in CircleCi.

We could use a parameterized job for connectors (https://circleci.com/docs/2.0/reusing-config/#using-the-parameters-declaration)

So we use something like:
```yaml
  # Connector parameterized depends on connector-base, mount workspace .m2
  connector:
    <<: *job_defaults
    environment:
      <<: *common_env
    parameters:
      artifact:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: syndesis-mvn-connector-{{ checksum "app/connector-<< parameters.artifact >>/pom.xml" }}
      - <<: *load_m2
      - run:
          name: Build Connector << parameters.artifact >>
          command: |
            ./tools/bin/syndesis build --batch-mode --module :<< parameters.artifact >> | tee build_log.txt
      - <<: *save_junit
      - store_test_results:
          path: /workspace/junit
      - store_artifacts:
          path: build_log.txt
      - save_cache:
          key: syndesis-mvn-connector-{{ checksum "app/connector-<< parameters.artifact >>/pom.xml" }}
          paths:
            - ~/.m2
      - <<: *save_m2
```

Notice the parameter `artifact` that is used to build only the specified Maven submodule with syndesis build script.

In the workflow definition we could explicitly list all connectors and let those run in parallel:

```yaml
workflows:
  version: 2
  syndesis:
    jobs:
      - system-test:
          filters:
            branches:
              only: system-test
      - doc:
          filters:
            branches:
              only: master
      - license-check
      - ui
      - ui-legacy
      - common
      - operator
      - extension:
          requires:
           - common
      - integration:
          requires:
            - extension
      - connector-base:
          requires:
            - integration
      - connector:
          artifact: connector-activemq
          requires:
            - connector-base
      - connector:
          artifact: connector-api-provider
          requires:
            - connector-base
      - connector:
          artifact: connector-amqp
          requires:
            - connector-base
      - connector:
          artifact: connector-aws-s3
          requires:
            - connector-base
      - connector:
          artifact: connector-aws-sqs
          requires:
            - connector-base
      - connector:
          artifact: connector-aws-sns
          requires:
            - connector-base
      - connector:
          artifact: connector-box
          requires:
            - connector-base
[...]
```

`connector-base` would be a job that runs connector support modules first. As all connector jobs depend on `connector-base` CircleCi would be able to run those in parallel.

Not sure though if this is working.

@zregvart @squakez WDYT?
