### ISSUE TITLE
Tag Error when executing latest operator

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#6597]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When compiling, building, deploying and executing the latest operator code in master, an error is generated:
```
{"level":"error","ts":1568388574.299153,"logger":"controller","msg":"Error reconciling","action":"*action.installAction","phase":"Installing","error":"./infrastructure/02-syndesis-image-streams.yml.tmpl: yaml: line 65: mapping values are not allowed in this context: 
<snip>
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: oauth-proxy
    labels:
      app: syndesis
      syndesis.io/app: syndesis
      syndesis.io/type: infrastructure
      syndesis.io/component: syndesis-oauthproxy
  spec:
    tags:
    - from:
        kind: DockerImage
        name: quay.io/openshift/origin-oauth-proxy:
      importPolicy:
        scheduled: true
      name: \"\"
<snip>
```
To start with I though it might be because **quay.io/openshift/origin-oauth-proxy:** was not in quotes unlike other similar properties so modified accordingly & got a different error.
```
{"level":"error","ts":1568498175.519641,"logger":"controller","msg":"Error reconciling","action":"*action.installAction","phase":"Installing","error":"ImageStream \"oauth-proxy\" is invalid: spec.tags[].from.name: Invalid value: \"quay.io/openshift/origin-oauth-proxy:\": invalid reference format","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tsrc/github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis.(*ReconcileSyndesis).Reconcile\n\tsrc/github.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis/syndesis_controller.go:120\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsrc/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tsrc/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tsrc/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tsrc/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\tsrc/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
The error is due to the property **.Syndesis.Spec.Components.Oauth.Tag** not being set when the templates are rendered. This was strange as it is set in [install.go](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/syndesis/action/install.go#L112) and (by debugging confirmed that it) remains in place until [here](https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/syndesis/action/install.go#L139). Once this function call is passed, that one tag gets reset to nothing.

Looking in Openshift itself, this is what I observed in the syndesis app:
```
oauth:
      tag: >-
      eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzeW5kZXNpcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJzeW5kZXNpcy1vYXV0aC1jbGllbnQtdG9rZW4teGp0cDUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoic3luZGVzaXMtb2F1dGgtY2xpZW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmMwYTE3NmUtZDczOC0xMWU5LWEzNTktNTI1NDAwMDU3ZDA3Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnN5bmRlc2lzOnN5bmRlc2lzLW9hdXRoLWNsaWVudCJ9.E9oTM7GCvfZR3AnEvKI5juhc4g765kx9NaJT-AQ4FJRzjjfjEYbnZEmlGdPEigqIb_XrBJxmKwhIDZDYkmL9ehexKq32dHEnZ3CwOlWCmH2SnIED9sb5sTpor-vZKguWPOY_t3CS4eT2muyJRUnSx-2INy8acfX-lufH0WTyYaPYZH-e4gelO3eIySv70xbXDS_R6nbfVcPd2Vlvxel-wqY6B6AWNV4kee8Uw0q32T1kk4OOpvVaFuPegwBFnj5HJWTBjgjIErn-Li1AgJqnd9oWygKTF89h9to94hSLE1rM_-jFEcdSsyDwVHpoe5ee1IAjjDpv0EwJOBxN-UEOvQ
prometheus:
  resources:
    limits:
      memory: 512Mi
    volumeCapacity: 1Gi
  tag: v2.1.0
...
```
The value of the Prometheus Tag matches that which it generated in the Syndesis CRD while the Oauth Tag is expected to be 4.4.0. So has something gone a little awry?
