### ISSUE TITLE
Integration with periodic invoke SQL logs mapper warning

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#792]
For such an integration with [mapping](https://gist.github.com/dsimansk/076afc0bdee3e53f8980d7dc6fb61d28). The integration itself seems to be working fine. Therefor it's rather cosmetic issue I guess.

Cc @KurtStam 

```
---
flows:
- steps:
  - kind: endpoint
    uri: sql-start-connector:SELECT * FROM CONTACT?schedulerPeriod=5000
  - kind: endpoint
    uri: atlas:mapping-step-2.json
  - kind: endpoint
    uri: sql-stored-connector:add_lead(VARCHAR ${body[first_and_last_name]}, VARCHAR ${body[company]}, VARCHAR ${body[phone]}, VARCHAR ${body[email]}, VARCHAR ${body[lead_source]}, VARCHAR ${body[lead_status]}, VARCHAR ${body[rating]})
```

Log warning:
```
2017-12-15 12:13:03.620  WARN 1 --- [ector-component] o.a.c.component.atlasmap.AtlasEndpoint   : There's no source document with docId='SQL_PARAM_OUT', returning default: docId='null', path='null'
```
