### ISSUE TITLE
Jaeger operator is spun up when jaeger addon disabled

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#8346]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When:
```
spec:
  addons:
    jaeger:
      disabled: true
```

The `jaeger-operator` Deployment and Pod are created. The only way to disable that is to set `clientOnly: true` on the jaeger addon.
