### ISSUE TITLE
AMQ: `Client ID` on connection prevents reuse of same JMS connection in integration 

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#889]
Hi @dhirajsb,
I wonder if moving `Client ID` property to create connection flow is a good idea from a usability standpoint. Currently I can't create e.g. `topic -> queue` integration on a same AMQ connection because, client ID gets propagated to both endpoints and exception is thrown.

```
flows:
- steps:
  - kind: endpoint
    uri: activemq-subscribe-1
    properties:
      destinationName: cheese
      destinationType: topic
      durableSubscriptionId: syndesis-client
      messageSelector: exampleSelector
  - kind: endpoint
    uri: activemq-publish-2
    properties:
      destinationName: food
      destinationType: queue
      persistent: "false"
```

application.properties
```
activemq-subscribe.configurations.activemq-subscribe-1.clientID=syndesis-client
activemq-publish.configurations.activemq-publish-2.clientID=syndesis-client
```

```

2018-01-03 11:05:43.936 ERROR 1 --- [           main] o.a.camel.component.sjms.SjmsConsumer    : Unable to create the MessageConsumer
--
  |  
  | javax.jms.JMSException: You cannot create a durable subscriber without specifying a unique clientID on a Connection


```

What is the difference between `Client ID` defined on Connection directly versus `Durable Subscription ID` provided configuring `Subscribe for messages` action? 

`Durable Subscription ID`seems to have no effect (prorably better to create a separate issue for it?).

Cc @jimmidyson fyi.
