### ISSUE TITLE
OpenAPI: nested array types not supported

### ISSUE THREAD

**Issue by lina2358** [syndesisio/syndesis#8920]
/cc @christophd 
https://github.com/syndesisio/syndesis/blob/1539c5af330f7abb8a4a641083640ea6e189842f/app/server/api-generator/src/main/java/io/syndesis/server/api/generator/openapi/v3/Oas30ParameterGenerator.java#L56-L62

This code elides the following valid spec case:

```yaml
      in: query
      name: filters
      schema:
        type: array
        items:
          type: array
          items:
            type: string
      description: |
        You can filter the listing using sql conditions by passing them as the filters GET param.
        Each condition is an array of the format, [{doctype}, {field}, {operator}, {value}].
        For example, filters=[["Customer", "country", "=", "India"]]
```

Reproducible with the following API: https://app.swaggerhub.com/apis/alyf.de/ERPNext/13#

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/31328370/89947704-85181680-dbea-11ea-8556-aaa63219e51c.png)

![image](https://user-images.githubusercontent.com/31328370/89947879-c14b7700-dbea-11ea-8b42-9678bbda709e.png)

</details>
