### ISSUE TITLE
Stuck in UpgradeFailed CR status

### ISSUE THREAD

**Issue by akraskovski** [syndesisio/syndesis#9981]
Hi everyone, need some help to move from stuck CR status "UpgradeFailed".

**Pre-condition**
We got a situation while operator reconciling the DB wasn't reachable.
So after 5 retry attempts of "Db upgrade" job execution it failed and set the status of Custom Resource to "Upgrade Failed".

```
apiVersion: syndesis.io/v1beta3
kind: Syndesis
...
status:
  backup: {}
  description: Upgrade failed too many times and will not be retried
  lastUpgradeFailure: '2023-01-30T10:13:36Z'
  phase: UpgradeFailed
  reason: TooManyUpgradeAttempts
  upgradeAttempts: 5
  version: 1.7.3.141.dev
```
Current DB state is OK. But the syndesis operator do nothing due to stuck CR status "UpgradeFailed"

**Problem**
The official guide says that: 
> **UpgradeFailed**: After the maximum amount of failed upgrades, the upgrade will not be tried anymore. The CR needs a manual action to move away from here

Can anyone help what does it mean: **The CR needs a manual action to move away from here**?
